---
- name: Update and Upgrade all repos and packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
    force_apt_get: yes
- name: Install Python3 and Pip3
  apt:
    update_cache: yes
    pkg:
      - python
      - python-pip
      - python-mysqldb
      - python-dev
      - python3
      - python3-pip
      - python3-mysqldb
      - python3-dev

- name: Install pymysql
  pip:
    name: pymysql
    state: present
- name: Install gdown
  pip:
    name: gdown
    state: present