---
- name: Create MagentoDB
  mysql_db:
    name: "{{ magento_db_name }}"
    state: present
- name: Create magento_db_user
  mysql_user:
    name: "{{ magento_db_user }}"
    password: "{{ magento_db_password }}"
    priv: "{{ magento_db_name_grants }}"
    state: present