---
- name: Create MagentoDB
  mysql_db:
    name: magentoDB
    state: present
- name: Create magento_db_user
  mysql_user:
    name: "{{ magento_db_user }}"
    password: "{{ magento_db_password }}"
    priv: magentoDB.*:ALL,GRANT
    state: present