---
- name: Creating www files
  file:
    path: /var/www/html/magento/
    group: www-data
    owner: www-data
    state: directory
- name: Creating Magento VirtualHost
  file:
    path: /etc/nginx/sites-available/magento
    state: touch
- name: Configuring Magento VirtualHost
  blockinfile:
    path: /etc/nginx/sites-available/magento
    block: |
      upstream fastcgi_backend {
        server  unix:/run/php/php7.1-fpm.sock; 
      }
      server {
      listen 80;
      listen [::]:80;
      index  index.php index.html index.htm;
      server_name  store.creez.com;
      client_max_body_size 100M;    
      set $MAGE_ROOT /var/www/html/magento;
      set $MAGE_MODE developer;
      include /var/www/html/magento/nginx.conf.sample;
      }
- name: Get Magento Source from gdrive
  shell:
    cmd: "gdown https://drive.google.com/uc?id={{ gfile_id }} -O /tmp/MagentoCE.tar.gz"
- name: Unarchive MagentoCe to www
  unarchive:
    src: /tmp/MagentoCE.tar.gz
    dest: /var/www/html/magento/
- name: Adjusting permissions on www
  file:
    path: /var/www/html/magento/
    owner: www-data
    group: www-data
    recurse: yes
- name: Create a symbolic link to sites-enabled
  file:
    src: /etc/nginx/sites-available/magento 
    dest: /etc/nginx/sites-enabled/magento
    state: link
- name: Adjusting nginx.conf.sample
  lineinfile:
    dest: /var/www/html/magento/nginx.conf.sample
    line: "	try_files $uri $uri/ /setup/index.php?$query_string;"
    insertafter: "/setup/index.php {"
    state: present
- name: Editing /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1  store.creez.com"
    insertafter: "^localhost"
    state: present

