---
- name: Editing `/etc/php/7.1/fpm/php.ini` memory_limit = 256M
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: "^memory_limit ="
    line: "memory_limit = 256M"
- name: Editing `/etc/php/7.1/fpm/php.ini` upload_max_filesize = 100M 
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: "^upload_max_filesize ="
    line: "upload_max_filesize = 100M" 
- name: Editing `/etc/php/7.1/fpm/php.ini` cgi.fix_pathinfo = 0
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: "^;cgi.fix_pathinfo =" 
    line: "cgi.fix_pathinfo = "
- name: Editing `/etc/php/7.1/fpm/php.ini` date.timezone = America/Sao_Paulo
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: "^;date.timezone =" 
    line: "date.timezone = America/Sao_Paulo" 
