---
- name: Add PPA PHP7.1
  apt_repository:
    validate_certs: no
    repo: "ppa:ondrej/php"
    state: present
- name: Install PHP 7.1
  apt:
    update_cache: yes
  apt:
    pkg:
      - software-properties-common
      - php7.1-bcmath
      - php7.1-fpm
      - php7.1-common
      - php7.1-mbstring
      - php7.1-xmlrpc
      - php7.1-soap
      - php7.1-gd
      - php7.1-xml
      - php7.1-intl
      - php7.1-mysql
      - php7.1-cli
      - php7.1-zip
      - php7.1-curl
      - php7.1-mcrypt